# Stage 1 - the build process
FROM node:14 as builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

# Stage 2 - the production environment
FROM node:14-alpine as prod
WORKDIR /app
COPY --from=builder /app .
EXPOSE 3000
CMD [ "node", "app.js" ]